Code Review
meghnaneelayavalasa/HomeTask1 pull request #1
Opened 2022-04-05 13:36 UTC by meghnaneelayavalasa

2022-04-06 12:18 UTC, SurajPareek01 reviewed
Good Work!, just address few review comments;

2022-04-06 12:18 UTC, SurajPareek01 commented on home_task1.html
> +        <hr width="93%">
inline css is not recommended?

2022-04-06 12:18 UTC, SurajPareek01 commented on news.css
> +    margin-top: 3%;
the percentage is not recommended as it might break in small size resolution; for responsive page design please use flex and media queries;

2022-04-21 11:18 UTC, SurajPareek01 requested changes
Please address the review comments.

2022-04-21 11:18 UTC, SurajPareek01 commented on home_task1.html
> +<<<<<<< Updated upstream
Please resolve merge conflicts properly.

2022-04-21 11:18 UTC, SurajPareek01 commented on news.css
> +    width: 90%;
do we really need to define width in % here?

2022-04-21 11:18 UTC, SurajPareek01 commented on news.css
> +    width: 900px;
do we really need to define width here?

2022-04-21 11:18 UTC, SurajPareek01 commented on home_task1.html
> +                <button type="button" class="btn 2" >Continue Reading</button>
please use the meaningful naming conventions for defining CSS classes.

2022-05-24 10:40 UTC, closed without merging

2022-05-24 10:40 UTC, meghnaneelayavalasa commented
Will open a new pull request